import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import type { PDFPage, PDFFont } from "pdf-lib";
import type { FormatSettings } from "../types/format";
import { effectivePaper, MARGIN_SIZES } from "../types/format";
import { ACCESS_DISCLAIMER } from "../types/access";
import type { Bounds } from "./geo";
import { getMagneticDeclination, currentDecimalYear } from "./wmm";
import type { SheetGrid, SheetCell } from "./sheetGrid";
import { computeSheetGrid } from "./sheetGrid";
import { renderMapImage } from "./renderMapImage";
import type { RasterLayer } from "./renderMapImage";
import {
  drawNeatline,
  drawTitleBlock,
  drawScaleBar,
  drawCompassRose,
  drawLegend,
  drawLatLonGrid,
  drawDisclaimerBlock,
  wrapText,
  type LegendEntry,
} from "./cartography";

const PT_PER_IN = 72;

// Vertical band heights (points)
const TITLE_H  = 42;   // title block
const SCALE_H  = 54;   // scale bar + legend band (a bit taller to fit km bar labels)
const DISC_H   = 44;   // mandatory disclaimer
const ROSE_R   = 34;   // compass rose radius in pts
// Gap between the disclaimer band and the scale-bar band above it — without
// this they sit flush against each other (scaleY used to start at exactly
// discY + DISC_H). Comes out of the map's own height budget below so the
// title block still lands flush with the top margin.
const DISC_SCALE_GAP_PT = 10;

export interface PdfBuildOptions {
  /** JPEG data URL from renderMapImage */
  mapJpegUrl: string;
  fmt: FormatSettings;
  scale: number;
}

/**
 * Backwards-compatible single-sheet PDF (Stage 11 format).
 * Use buildCartographicPdf for the full Stage 12 layout.
 */
export async function buildSingleSheetPdf(opts: PdfBuildOptions): Promise<Uint8Array> {
  const { mapJpegUrl, fmt, scale } = opts;

  const paper   = effectivePaper(fmt);
  const pageW   = paper.w * PT_PER_IN;
  const pageH   = paper.h * PT_PER_IN;
  const marginPt = (MARGIN_SIZES[fmt.margins] ?? 0.5) * PT_PER_IN;

  const usableW = pageW  - marginPt * 2;
  const usableH = pageH  - marginPt * 2;
  const discH   = 0.55   * PT_PER_IN;
  const mapH    = usableH - discH;

  const doc  = await PDFDocument.create();
  doc.setTitle("Hunting Map");
  doc.setCreator("Hunting Map Generator");
  const page = doc.addPage([pageW, pageH]);
  page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });

  const b64      = mapJpegUrl.split(",")[1] ?? "";
  const jpegBytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const jpegImage = await doc.embedJpg(jpegBytes);

  page.drawImage(jpegImage, { x: marginPt, y: marginPt + discH, width: usableW, height: mapH });
  page.drawRectangle({ x: marginPt, y: marginPt + discH, width: usableW, height: mapH, borderColor: rgb(0.6, 0.6, 0.6), borderWidth: 0.5 });

  const font     = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const warnRed  = rgb(0.60, 0.08, 0.08);
  const innerW   = usableW - 16;
  const fSize    = 6.5;
  const lineH    = fSize * 1.45;
  const wLabel   = "WARNING: ";
  const wLabelW  = fontBold.widthOfTextAtSize(wLabel, fSize);
  const lines    = wrapText(ACCESS_DISCLAIMER, font, fSize, innerW - wLabelW);

  let ty = marginPt + discH - 6 - fSize;
  for (let i = 0; i < lines.length; i++) {
    if (i === 0) {
      page.drawText(wLabel, { x: marginPt + 8, y: ty, font: fontBold, size: fSize, color: warnRed });
      page.drawText(lines[i], { x: marginPt + 8 + wLabelW, y: ty, font, size: fSize, color: warnRed });
    } else {
      page.drawText(lines[i], { x: marginPt + 8 + wLabelW, y: ty, font, size: fSize, color: warnRed });
    }
    ty -= lineH;
  }

  const note  = `Scale 1:${scale.toLocaleString()}  |  Generated by Hunting Map Generator`;
  const noteW = font.widthOfTextAtSize(note, 5.5);
  page.drawText(note, { x: marginPt + usableW - noteW - 6, y: marginPt + 4, font, size: 5.5, color: rgb(0.5, 0.5, 0.5) });

  return doc.save();
}

// ---------------------------------------------------------------------------
// Stage 12: Cartographic PDF
// ---------------------------------------------------------------------------

export interface CartographicPdfOptions {
  mapJpegUrl:   string;
  fmt:          FormatSettings;
  scale:        number;
  projectName:  string;
  subtitle:     string;    // e.g. "Colorado · Larimer County"
  centerLng:    number;
  centerLat:    number;
  bounds:       Bounds;    // geographic extent of the map image
  legendEntries: LegendEntry[];
}

export async function buildCartographicPdf(opts: CartographicPdfOptions): Promise<Uint8Array> {
  const { mapJpegUrl, fmt, scale, projectName, subtitle, bounds, legendEntries } = opts;

  const paper    = effectivePaper(fmt);
  const pageW    = paper.w   * PT_PER_IN;
  const pageH    = paper.h   * PT_PER_IN;
  const marginPt = (MARGIN_SIZES[fmt.margins] ?? 0.5) * PT_PER_IN;

  const usableW  = pageW - marginPt * 2;
  const usableH  = pageH - marginPt * 2;

  // Band Y positions (from bottom of page)
  const discY   = marginPt;
  const scaleY  = discY  + DISC_H + DISC_SCALE_GAP_PT;
  const mapY    = scaleY + SCALE_H;
  const titleY  = mapY   + (usableH - TITLE_H - SCALE_H - DISC_H - DISC_SCALE_GAP_PT);
  const mapH    = titleY - mapY;

  const mapX    = marginPt;
  const mapW    = usableW;

  const doc  = await PDFDocument.create();
  doc.setTitle(projectName);
  doc.setCreator("Hunting Map Generator");
  doc.setProducer("pdf-lib");
  const page = doc.addPage([pageW, pageH]);

  // White background
  page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });

  const font     = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  // ── Map image ──────────────────────────────────────────────────────────────
  const b64       = mapJpegUrl.split(",")[1] ?? "";
  const jpegBytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const jpegImage = await doc.embedJpg(jpegBytes);
  page.drawImage(jpegImage, { x: mapX, y: mapY, width: mapW, height: mapH });

  // ── Lat/lon grid ───────────────────────────────────────────────────────────
  drawLatLonGrid(page, { mapX, mapY, mapW, mapH, bounds, font });

  // ── Neatline (drawn on top of map / grid) ─────────────────────────────────
  drawNeatline(page, mapX, mapY, mapW, mapH);

  // ── Compass rose (top-right corner of map, overlaid) ──────────────────────
  const decl = getMagneticDeclination(
    opts.centerLat, opts.centerLng, 0, currentDecimalYear(),
  );
  drawCompassRose(page, {
    cx: mapX + mapW - ROSE_R - 8,
    cy: mapY + mapH - ROSE_R - 8,
    radius: ROSE_R,
    declDeg: decl,
    font,
    fontBold,
  });

  // ── Title block (top band) ─────────────────────────────────────────────────
  const now     = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
  drawTitleBlock(page, {
    x: mapX, y: titleY, width: mapW, height: TITLE_H,
    title: projectName, subtitle,
    scale, dateStr, sheetRef: "Sheet 1 of 1",
    font, fontBold,
  });

  // ── Scale bar + legend (bottom sub-band above disclaimer) ─────────────────
  drawScaleBar(page, {
    x: mapX + 8, y: scaleY,
    font, scale, pageWidthPt: mapW,
  });

  const LEGEND_W = Math.min(160, mapW * 0.3);
  drawLegend(page, {
    x: mapX + mapW - LEGEND_W - 4,
    y: scaleY,
    width: LEGEND_W,
    entries: legendEntries,
    font, fontBold,
  });

  // ── Disclaimer (mandatory §6.3) ────────────────────────────────────────────
  drawDisclaimerBlock(page, mapX, discY, mapW, DISC_H, ACCESS_DISCLAIMER, font, fontBold);

  return doc.save();
}

// ---------------------------------------------------------------------------
// Stage 13: Multi-sheet PDF
// ---------------------------------------------------------------------------

const DEFAULT_OVERLAP_IN = 0.5;

export interface MultiSheetPdfOptions extends Omit<CartographicPdfOptions, "mapJpegUrl" | "bounds"> {
  rasterLayers: RasterLayer[];
  overlapIn?: number;
  dpi?: number;
  onProgress?: (detail: string, current: number, total: number) => void;
}

export async function buildMultiSheetPdf(opts: MultiSheetPdfOptions): Promise<Uint8Array> {
  const { fmt, scale, rasterLayers, legendEntries } = opts;
  const overlapIn = opts.overlapIn ?? DEFAULT_OVERLAP_IN;
  const DPI = opts.dpi ?? 150;

  const grid = computeSheetGrid(fmt, overlapIn, opts.centerLng, opts.centerLat, scale);
  const { mapWidthIn, mapHeightIn, totalBounds, cells, totalSheets } = grid;

  const paper    = effectivePaper(fmt);
  const pageW    = paper.w   * PT_PER_IN;
  const pageH    = paper.h   * PT_PER_IN;
  const marginPt = (MARGIN_SIZES[fmt.margins] ?? 0.5) * PT_PER_IN;
  const usableW  = pageW - marginPt * 2;
  const usableH  = pageH - marginPt * 2;

  const discY   = marginPt;
  const scaleY  = discY  + DISC_H + DISC_SCALE_GAP_PT;
  const mapY    = scaleY + SCALE_H;
  const mapH    = usableH - TITLE_H - SCALE_H - DISC_H - DISC_SCALE_GAP_PT;
  const mapX    = marginPt;
  const mapW    = usableW;

  const pixelW = Math.round(mapWidthIn  * DPI);
  const pixelH = Math.round(mapHeightIn * DPI);

  const now     = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
  const decl    = getMagneticDeclination(opts.centerLat, opts.centerLng, 0, currentDecimalYear());

  const doc      = await PDFDocument.create();
  doc.setTitle(opts.projectName);
  doc.setCreator("Hunting Map Generator");
  doc.setProducer("pdf-lib");

  const font     = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  // total progress = 1 overview + N sheets
  const totalSteps = 1 + totalSheets;

  // ── Page 1: Overview sheet ─────────────────────────────────────────────────
  opts.onProgress?.("Rendering overview sheet…", 0, totalSteps);

  const ovPixelW = Math.round(mapWidthIn  * grid.cols * DPI);
  const ovPixelH = Math.round(mapHeightIn * grid.rows * DPI);
  const ovJpeg   = await renderMapImage({ bounds: totalBounds, pixelW: ovPixelW, pixelH: ovPixelH, rasterLayers });

  const ovPage = doc.addPage([pageW, pageH]);
  ovPage.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });

  const ovB64     = ovJpeg.split(",")[1] ?? "";
  const ovBytes   = Uint8Array.from(atob(ovB64), (c) => c.charCodeAt(0));
  const ovImage   = await doc.embedJpg(ovBytes);
  ovPage.drawImage(ovImage, { x: mapX, y: mapY, width: mapW, height: mapH });

  // Grid overlay on overview
  drawOverviewGrid(ovPage, mapX, mapY, mapW, mapH, grid, fontBold);
  drawNeatline(ovPage, mapX, mapY, mapW, mapH);

  drawTitleBlock(ovPage, {
    x: mapX, y: mapY + mapH, width: mapW, height: TITLE_H,
    title: opts.projectName,
    subtitle: `${opts.subtitle}   |   Overview — ${totalSheets} sheets`,
    scale, dateStr, sheetRef: `1 of ${totalSheets + 1}`,
    font, fontBold,
  });
  drawScaleBar(ovPage, { x: mapX + 8, y: scaleY, font, scale, pageWidthPt: mapW });
  drawDisclaimerBlock(ovPage, mapX, discY, mapW, DISC_H, ACCESS_DISCLAIMER, font, fontBold);

  // ── Pages 2..N: individual sheets ─────────────────────────────────────────
  for (let i = 0; i < cells.length; i++) {
    const cell = cells[i];
    opts.onProgress?.(
      `Rendering sheet ${cell.ref} (${i + 1} of ${totalSheets})…`,
      i + 1,
      totalSteps,
    );

    const jpegUrl = await renderMapImage({ bounds: cell.bounds, pixelW, pixelH, rasterLayers });
    const b64     = jpegUrl.split(",")[1] ?? "";
    const jBytes  = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    const jImage  = await doc.embedJpg(jBytes);

    const page = doc.addPage([pageW, pageH]);
    page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });
    page.drawImage(jImage, { x: mapX, y: mapY, width: mapW, height: mapH });

    drawLatLonGrid(page, { mapX, mapY, mapW, mapH, bounds: cell.bounds, font });
    drawNeatline(page, mapX, mapY, mapW, mapH);

    drawCompassRose(page, {
      cx: mapX + mapW - ROSE_R - 8,
      cy: mapY + mapH - ROSE_R - 8,
      radius: ROSE_R,
      declDeg: decl,
      font, fontBold,
    });

    drawEdgeMatchMarkers(page, mapX, mapY, mapW, mapH, cell, font);

    drawTitleBlock(page, {
      x: mapX, y: mapY + mapH, width: mapW, height: TITLE_H,
      title: opts.projectName,
      subtitle: `${opts.subtitle}   |   Sheet ${cell.ref}`,
      scale, dateStr,
      sheetRef: `Sheet ${cell.ref} — Page ${cell.pageIndex} of ${totalSheets + 1}`,
      font, fontBold,
    });

    drawScaleBar(page, { x: mapX + 8, y: scaleY, font, scale, pageWidthPt: mapW });

    const LEGEND_W = Math.min(140, mapW * 0.28);
    drawLegend(page, { x: mapX + mapW - LEGEND_W - 4, y: scaleY, width: LEGEND_W, entries: legendEntries, font, fontBold });

    drawIndexInset(page, mapX + mapW - LEGEND_W - 80, scaleY, grid, cell, font);

    drawDisclaimerBlock(page, mapX, discY, mapW, DISC_H, ACCESS_DISCLAIMER, font, fontBold);
  }

  return doc.save();
}

// ---------------------------------------------------------------------------
// Multi-sheet drawing helpers
// ---------------------------------------------------------------------------

function drawOverviewGrid(
  page: PDFPage,
  mapX: number, mapY: number, mapW: number, mapH: number,
  grid: SheetGrid,
  fontBold: PDFFont,
) {
  const { rows, cols, cells } = grid;
  const cellW = mapW / cols;
  const cellH = mapH / rows;
  const grey  = rgb(0.3, 0.3, 0.3);
  const white = rgb(1, 1, 1);

  // Vertical division lines
  for (let c = 1; c < cols; c++) {
    const x = mapX + c * cellW;
    for (let y = mapY; y < mapY + mapH; y += 7) {
      page.drawLine({
        start: { x, y: Math.min(y, mapY + mapH - 1) },
        end:   { x, y: Math.min(y + 4, mapY + mapH - 1) },
        thickness: 1, color: grey,
      });
    }
  }

  // Horizontal division lines
  for (let r = 1; r < rows; r++) {
    const y = mapY + (rows - r) * cellH;
    for (let x = mapX; x < mapX + mapW; x += 7) {
      page.drawLine({
        start: { x: Math.min(x, mapX + mapW - 1), y },
        end:   { x: Math.min(x + 4, mapX + mapW - 1), y },
        thickness: 1, color: grey,
      });
    }
  }

  // Cell reference labels
  for (const cell of cells) {
    const cx = mapX + cell.col * cellW + cellW / 2;
    const cy = mapY + (rows - 1 - cell.row) * cellH + cellH / 2;
    const lbl = cell.ref;
    const lw = fontBold.widthOfTextAtSize(lbl, 14);
    const lh = 14;

    // Drop shadow / background
    page.drawRectangle({
      x: cx - lw / 2 - 3, y: cy - 2,
      width: lw + 6, height: lh + 4,
      color: white, borderColor: grey, borderWidth: 0.4,
    });
    page.drawText(lbl, {
      x: cx - lw / 2, y: cy,
      font: fontBold, size: lh, color: rgb(0.1, 0.1, 0.1),
    });
  }
}

function drawEdgeMatchMarkers(
  page: PDFPage,
  mapX: number, mapY: number, mapW: number, mapH: number,
  cell: SheetCell,
  font: PDFFont,
) {
  const grey = rgb(0.3, 0.3, 0.3);
  const sz   = 6.5;
  const PAD  = 3;

  // Standard-14 PDF fonts (Helvetica here) are WinAnsi-encoded and cannot
  // render arrow glyphs (U+2190..U+2193) — pdf-lib throws at drawText() for
  // any sheet with a neighbor in any direction, which is nearly every sheet
  // in a multi-sheet layout. Verified against pdf-lib's actual encoder: `^`
  // `v` `<` `>` are plain ASCII and always safe.
  if (cell.north) {
    const lbl = `^ Sheet ${cell.north}`;
    const lw  = font.widthOfTextAtSize(lbl, sz);
    page.drawText(lbl, { x: mapX + mapW / 2 - lw / 2, y: mapY + mapH + PAD, font, size: sz, color: grey });
  }
  if (cell.south) {
    const lbl = `v Sheet ${cell.south}`;
    const lw  = font.widthOfTextAtSize(lbl, sz);
    page.drawText(lbl, { x: mapX + mapW / 2 - lw / 2, y: mapY - sz - PAD, font, size: sz, color: grey });
  }
  if (cell.west) {
    const lbl = `< Sheet ${cell.west}`;
    page.drawText(lbl, { x: mapX - font.widthOfTextAtSize(lbl, sz) - PAD, y: mapY + mapH / 2 - sz / 2, font, size: sz, color: grey });
  }
  if (cell.east) {
    const lbl = `> Sheet ${cell.east}`;
    page.drawText(lbl, { x: mapX + mapW + PAD, y: mapY + mapH / 2 - sz / 2, font, size: sz, color: grey });
  }
}

function drawIndexInset(
  page: PDFPage,
  x: number, y: number,
  grid: SheetGrid,
  current: SheetCell,
  font: PDFFont,
) {
  const { rows, cols } = grid;
  const insetH  = Math.min(SCALE_H - 6, 48);
  const insetW  = Math.round(insetH * (cols / rows));
  const cellW   = insetW / cols;
  const cellH   = insetH / rows;

  const grey  = rgb(0.75, 0.75, 0.75);
  const hi    = rgb(0.18, 0.44, 0.76);
  const black = rgb(0, 0, 0);
  const white = rgb(1, 1, 1);

  // Background
  page.drawRectangle({ x, y, width: insetW, height: insetH, color: white, borderColor: black, borderWidth: 0.5 });

  for (const cell of grid.cells) {
    const cx = x + cell.col * cellW;
    const cy = y + (rows - 1 - cell.row) * cellH;
    const isThis = cell.row === current.row && cell.col === current.col;

    page.drawRectangle({
      x: cx, y: cy, width: cellW, height: cellH,
      color: isThis ? hi : grey,
      borderColor: black, borderWidth: 0.3,
    });

    if (cellW > 10) {
      const lbl = cell.ref;
      const lw  = font.widthOfTextAtSize(lbl, 4);
      page.drawText(lbl, {
        x: cx + cellW / 2 - lw / 2, y: cy + cellH / 2 - 2,
        font, size: 4, color: isThis ? white : black,
      });
    }
  }
}
